grpc_server_config:
  name: "post-sbs:1"
  address: ":9130"
  discovery_ex_config:
    external_address: "127.0.0.1"
grpc_client_config_tpl:
redis_dsn: "redis://:redis_default_pass@env.dev:8900/0"
discovery_server_names:
  "post": "post"

signer: "羊米"
